## YAML Template.
databaseChangeLog:
    - changeSet:
        id: 1.0.0
        author: jim.talbut
        changes:
        - createTable:
            tableName: ClientMessageLog
            columns:
                - column: { name: Id, type: bigint, autoIncrement: true, constraints: { primaryKey: true, nullable: false } }

                - column: {name: CorrelationId, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Jvm, type: nvarchar(1024), constraints: { nullable: false } }
                - column: {name: Method, type: nvarchar(32), constraints: { nullable: false } }
                - column: {name: Url, type: nvarchar(1024), constraints: { nullable: false } }
                - column: {name: LocalIp, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: RemoteIp, type: nvarchar(64), constraints: { nullable: false } }

                - column: {name: RequestStartDateTime, type: datetime, constraints: { nullable: false } }
                - column: {name: RequestHeaders, type: nclob, constraints: { nullable: true } }
                - column: {name: RequestHost, type: nvarchar(256), constraints: { nullable: true } }
                - column: {name: RequestContentType, type: nvarchar(256), constraints: { nullable: true } }
                
                - column: {name: Username, type: nvarchar(64), constraints: { nullable: true } }
                - column: {name: RequestCompleteDateTime, type: datetime, constraints: { nullable: true } }
                - column: {name: RequestBody, type: blob, constraints: { nullable: true } }
                
                - column: {name: ResponseStartDateTime, type: datetime, constraints: { nullable: true } }
                - column: {name: ResponseHeaders, type: nclob, constraints: { nullable: true } }
                - column: {name: ResponseStatusCode, type: int, constraints: { nullable: true } }
                - column: {name: ResponseContentType, type: nvarchar(256), constraints: { nullable: true } }

                - column: {name: ResponseCompleteDateTime, type: datetime, constraints: { nullable: true } }
                - column: {name: ResponseBody, type: blob, constraints: { nullable: true } }
                
        - createTable:
            tableName: User
            columns:
                - column: {name: Username, type: nvarchar(64), constraints: { primaryKey: true, nullable: false } }
                - column: {name: Source, type: nvarchar(128), constraints: { nullable: false } }
                - column: {name: SourceId, type: nvarchar(128), constraints: { nullable: false } }
                - column: {name: Password, type: nvarchar(128), constraints: { nullable: true } }
                - column: {name: Email, type: nvarchar(128), constraints: { nullable: true } }
                - column: {name: FirstName, type: nvarchar(64), constraints: { nullable: true } }
                - column: {name: LastName, type: nvarchar(64), constraints: { nullable: true } }
                - column: {name: CreatedAt, type: datetime, constraints: { nullable: false } }
                - column: {name: UpdatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: LastConnectionAt, type: datetime, constraints: { nullable: true } }
                - column: {name: Picture, type: nclob, constraints: { nullable: true } }

        - createTable:
            tableName: UserRole
            columns:
                - column: {name: Username, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Role, type: nvarchar(64), constraints: { nullable: false } }

        - addPrimaryKey:
            columnNames: Username, Role
            tableName: UserRole

        - createTable:
            tableName: Api
            columns:
                - column: {name: Id, type: nvarchar(64), constraints: { primaryKey: true, nullable: false } }
                - column: {name: Name, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Description, type: nvarchar(2048), constraints: { nullable: false } }
                - column: {name: Version, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Definition, type: nclob, constraints: { nullable: false } }
                - column: {name: DeployedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: CreatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: UpdatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: Visibility, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: LifecycleState, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Picture, type: nclob, constraints: { nullable: true } }
                - column: {name: Group, type: nvarchar(64), constraints: { nullable: true } }

        - createTable:
            tableName: ApiView
            columns:
                - column: {name: ApiId, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: View, type: nvarchar(64), constraints: { nullable: false } }

        - addPrimaryKey:
            columnNames: ApiId, View
            tableName: ApiView

        - createTable:
            tableName: ApiTag
            columns:
                - column: {name: ApiId, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Tag, type: nvarchar(64), constraints: { nullable: false } }

        - addPrimaryKey:
            columnNames: ApiId, Tag
            tableName: ApiTag

        - createTable:
            tableName: ApiKey
            columns:
                - column: {name: Key, type: nvarchar(64), constraints: { primaryKey: true, nullable: false } }
                - column: {name: Subscription, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Application, type: nvarchar(2048), constraints: { nullable: false } }
                - column: {name: Plan, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: ExpireAt, type: datetime, constraints: { nullable: true } }
                - column: {name: CreatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: UpdatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: Revoked, type: bit, constraints: { nullable: false } }
                - column: {name: RevokedAt, type: datetime, constraints: { nullable: true } }

        - createTable:
            tableName: Event
            columns:
                - column: {name: Id, type: nvarchar(64), constraints: { primaryKey: true, nullable: false } }
                - column: {name: Type, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Payload, type: nclob, constraints: { nullable: false } }
                - column: {name: ParentId, type: nvarchar(64), constraints: { nullable: true } }
                - column: {name: CreatedAt, type: datetime, constraints: { nullable: false } }
                - column: {name: UpdatedAt, type: datetime, constraints: { nullable: false } }

        - createTable:
            tableName: EventProperty
            columns:
                - column: {name: EventId, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: PropertyName, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: PropertyValue, type: nvarchar(256), constraints: { nullable: true } }

        - addPrimaryKey:
            columnNames: EventId, PropertyName
            tableName: EventProperty

        - createTable:
            tableName: View
            columns:
                - column: {name: Id, type: nvarchar(64), constraints: { primaryKey: true, nullable: false } }
                - column: {name: Name, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Description, type: nvarchar(4000), constraints: { nullable: tur } }

        - createTable:
            tableName: Tag
            columns:
                - column: {name: Id, type: nvarchar(64), constraints: { primaryKey: true, nullable: false } }
                - column: {name: Name, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Description, type: nvarchar(4000), constraints: { nullable: tur } }

        - createTable:
            tableName: Tenant
            columns:
                - column: {name: Id, type: nvarchar(64), constraints: { primaryKey: true, nullable: false } }
                - column: {name: Name, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Description, type: nvarchar(4000), constraints: { nullable: tur } }

        - createTable:
            tableName: Application
            columns:
                - column: {name: Id, type: nvarchar(64), constraints: { primaryKey: true, nullable: false } }
                - column: {name: Name, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Description, type: nvarchar(4000), constraints: { nullable: true } }
                - column: {name: Type, type: nvarchar(64), constraints: { nullable: true } }
                - column: {name: Group, type: nvarchar(64), constraints: { nullable: true } }
                - column: {name: CreatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: UpdatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: Status, type: nvarchar(64), constraints: { nullable: true } }

        - createTable:
            tableName: Group
            columns:
                - column: {name: Id, type: nvarchar(64), constraints: { primaryKey: true, nullable: false } }
                - column: {name: Name, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Type, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: CreatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: UpdatedAt, type: datetime, constraints: { nullable: true } }

        - createTable:
            tableName: GroupAdministrator
            columns:
                - column: {name: GroupId, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Administrator, type: nvarchar(64), constraints: { nullable: false } }

        - addPrimaryKey:
            columnNames: GroupId, Administrator
            tableName: GroupAdministrator

        - createTable:
            tableName: Membership
            columns:
                - column: {name: UserId, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: ReferenceId, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: ReferenceType, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Type, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: CreatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: UpdatedAt, type: datetime, constraints: { nullable: true } }

        - addPrimaryKey:
            columnNames: UserId, ReferenceType, ReferenceId 
            tableName: Membership


        - createTable:
            tableName: Page
            columns:
                - column: {name: Id, type: nvarchar(64), constraints: { primaryKey: true, nullable: false } }
                - column: {name: Type, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Name, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Content, type: nclob, constraints: { nullable: false } }
                - column: {name: LastContributor, type: nvarchar(64), constraints: { nullable: true } }
                - column: {name: Order, type: int, constraints: { nullable: false } }
                - column: {name: Api, type: nvarchar(64), constraints: { nullable: true } }
                - column: {name: Published, type: bit, constraints: { nullable: false } }
                - column: {name: SourceType, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: SourceConfiguration, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: ConfigurationTryItURL, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: ConfigurationTryIt, type: bit, constraints: { nullable: false } }
                - column: {name: CreatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: UpdatedAt, type: datetime, constraints: { nullable: true } }

        - createTable:
            tableName: Plan
            columns:
                - column: {name: Id, type: nvarchar(64), constraints: { primaryKey: true, nullable: false } }
                - column: {name: Type, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Name, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Description, type: nclob, constraints: { nullable: false } }
                - column: {name: Validation, type: nvarchar(64), constraints: { nullable: true } }
                - column: {name: Definition, type: nclob, constraints: { nullable: false } }
                - column: {name: Order, type: int, constraints: { nullable: true } }
                - column: {name: Status, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Security, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: CreatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: UpdatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: PublishedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: ClosedAt, type: datetime, constraints: { nullable: true } }

        - createTable:
            tableName: PlanApi
            columns:
                - column: {name: PlanId, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Api, type: nvarchar(64), constraints: { nullable: false } }

        - addPrimaryKey:
            columnNames: PlanId, Api
            tableName: PlanApi

        - createTable:
            tableName: PlanCharacteristic
            columns:
                - column: {name: PlanId, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Characteristic, type: nvarchar(64), constraints: { nullable: false } }
        
        - addPrimaryKey:
            columnNames: PlanId, Characteristic
            tableName: PlanCharacteristic

        - createTable:
            tableName: Subscription
            columns:
                - column: {name: Id, type: nvarchar(64), constraints: { primaryKey: true, nullable: false } }
                - column: {name: Plan, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Application, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: StartingAt, type: datetime, constraints: { nullable: true } }
                - column: {name: EndingAt, type: datetime, constraints: { nullable: true } }
                - column: {name: CreatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: UpdatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: ProcessedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: ProcessedBy, type: nvarchar(64), constraints: { nullable: true } }
                - column: {name: SubscribedBy, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Reason, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Status, type: nvarchar(64), constraints: { nullable: false } }

        - createTable:
            tableName: RateLimit
            columns:
                - column: {name: Key, type: nvarchar(64), constraints: { primaryKey: true, nullable: false } }
                - column: {name: Counter, type: long, constraints: { nullable: false } }
                - column: {name: LastRequest, type: long, constraints: { nullable: false } }
                - column: {name: ResetTime, type: long, constraints: { nullable: false } }
                - column: {name: CreatedAt, type: long, constraints: { nullable: false } }
                - column: {name: UpdatedAt, type: long, constraints: { nullable: false } }
                - column: {name: Async, type: bit, constraints: { nullable: false } }
