## YAML Template.
databaseChangeLog:
    - changeSet:
        id: 1.4.0
        author: jim.talbut
        changes:

        - createTable:
            tableName: Metadata
            columns:
                - column: {name: Key, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: ReferenceType, type: nvarchar(32), constraints: { nullable: false } }
                - column: {name: ReferenceId, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Name, type: nvarchar(1024), constraints: { nullable: false } }
                - column: {name: Format, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Value, type: nvarchar(1024), constraints: { nullable: true } }
                
                - column: {name: CreatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: UpdatedAt, type: datetime, constraints: { nullable: true } }

        - addPrimaryKey:
            columnNames: Key, ReferenceType, ReferenceId 
            tableName: Metadata


        - createTable:
            tableName: ApiLabel
            columns:
                - column: {name: ApiId, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Label, type: nvarchar(64), constraints: { nullable: false } }

        - addPrimaryKey:
            columnNames: ApiId, Label
            tableName: ApiLabel

