## YAML Template.
databaseChangeLog:
    - changeSet:
        id: 1.7.0
        author: jim.talbut
        changes:

        - createTable:
            tableName: Audit
            columns:
                - column: {name: Id, type: nvarchar(64), constraints: { nullable: false, primaryKey: true } }
                - column: {name: ReferenceId, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: ReferenceType, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Username, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: CreatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: Event, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Patch, type: nvarchar(64), constraints: { nullable: false } }

        - createTable:
            tableName: AuditProperty
            columns:
                - column: {name: AuditId, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Key, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Value, type: nvarchar(200), constraints: { nullable: false } }

        - addPrimaryKey:
            columnNames: AuditId, Key, Value
            tableName: AuditProperty

        - createTable:
            tableName: Rating
            columns:
                - column: {name: Id, type: nvarchar(64), constraints: { nullable: false, primaryKey: true } }
                - column: {name: Api, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: User, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Rate, type: tinyint, constraints: { nullable: false } }
                - column: {name: Title, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Comment, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: CreatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: UpdatedAt, type: datetime, constraints: { nullable: true } }

        - createTable:
            tableName: RatingAnswer
            columns:
                - column: {name: Id, type: nvarchar(64), constraints: { nullable: false, primaryKey: true } }
                - column: {name: Rating, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: User, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Comment, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: CreatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: UpdatedAt, type: datetime, constraints: { nullable: true } }
    
        - createTable:
            tableName: PageExcludedGroup
            columns:
                - column: {name: PageId, type: nvarchar(64), constraints: { nullable: false, primaryKey: true } }
                - column: {name: ExcludedGroup, type: nvarchar(64), constraints: { nullable: false, primaryKey: true } }
    
        - createTable:
            tableName: PlanExcludedGroup
            columns:
                - column: {name: PlanId, type: nvarchar(64), constraints: { nullable: false, primaryKey: true } }
                - column: {name: ExcludedGroup, type: nvarchar(64), constraints: { nullable: false, primaryKey: true } }
    
        - addColumn:
            tableName: View
            columns:
                - column: {name: DefaultView, type: boolean, constraints: { nullable: true } }
                - column: {name: Hidden, type: bit, constraints: { nullable: true } }
                - column: {name: Order, type: int, constraints: { nullable: true } }
                - column: {name: CreatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: UpdatedAt, type: datetime, constraints: { nullable: true } }
