## YAML Template.
databaseChangeLog:
    - changeSet:
        id: 1.6.0
        author: jim.talbut
        changes:

        - createTable:
            tableName: GroupEventRule
            columns:
                - column: {name: GroupId, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: GroupEvent, type: nvarchar(64), constraints: { nullable: false } }

        - createTable:
            tableName: ApiGroup
            columns:
                - column: {name: ApiId, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: GroupId, type: nvarchar(64), constraints: { nullable: false } }

        - createTable:
            tableName: ApplicationGroup
            columns:
                - column: {name: ApplicationId, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: GroupId, type: nvarchar(64), constraints: { nullable: false } }

        - createTable:
            tableName: MembershipRole
            columns:
                - column: {name: UserId, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: ReferenceId, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: ReferenceType, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: RoleScope, type: int, constraints: { nullable: false } }
                - column: {name: RoleName, type: nvarchar(64), constraints: { nullable: false } }

        - addPrimaryKey:
            columnNames: UserId, ReferenceType, ReferenceId, RoleScope
            tableName: MembershipRole

        - dropColumn:
            tableName: Group
            columnName: Type 

        - dropColumn:
            tableName: Api
            columnName: Group

        - dropColumn:
            tableName: Application
            columnName: Group

        - dropColumn:
            tableName: Membership
            columnName: RoleScope 

        - dropColumn:
            tableName: Membership
            columnName: RoleName

