## YAML Template.
databaseChangeLog:
    - changeSet:
        id: 1.5.0
        author: jim.talbut
        changes:

        - addColumn:
            tableName: Membership
            columns:
                - column: {name: RoleScope, type: int, constraints: { nullable: true } }
                - column: {name: RoleName, type: nvarchar(64), constraints: { nullable: true } }

        - createTable:
            tableName: Role
            columns:
                - column: {name: Scope, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: Name, type: nvarchar(128), constraints: { nullable: false } }
                - column: {name: Description, type: nvarchar(1024), constraints: { nullable: true } }
                - column: {name: DefaultRole, type: bit, constraints: { nullable: false, default: 0 } }
                - column: {name: System, type: bit, constraints: { nullable: false, default: 0 } }
                - column: {name: CreatedAt, type: datetime, constraints: { nullable: true } }
                - column: {name: UpdatedAt, type: datetime, constraints: { nullable: true } }

        - addPrimaryKey:
            columnNames: Scope, Name
            tableName: Role

        - createTable:
            tableName: RolePermission
            columns:
                - column: {name: RoleScope, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: RoleName, type: nvarchar(128), constraints: { nullable: false } }
                - column: {name: Permission, type: nvarchar(64), constraints: { nullable: false } }

        - addPrimaryKey:
            columnNames: RoleScope, RoleName, Permission
            tableName: RolePermission
