## YAML Template.
databaseChangeLog:
    - changeSet:
        id: 1.2.0
        author: jim.talbut
        changes:

        - dropNotNullConstraint: {tableName: User, columnName: Source, columnDataType: nvarchar(128) }
        - dropNotNullConstraint: {tableName: User, columnName: SourceId, columnDataType: nvarchar(128) }

        - dropNotNullConstraint: {tableName: Api, columnName: Name, columnDataType: nvarchar(64) }
        - dropNotNullConstraint: {tableName: Api, columnName: Description, columnDataType: nvarchar(2048) }

        - dropNotNullConstraint: {tableName: ApiKey, columnName: Subscription, columnDataType: nvarchar(64) }
        - dropNotNullConstraint: {tableName: ApiKey, columnName: Application, columnDataType: nvarchar(2048) }
        - dropNotNullConstraint: {tableName: ApiKey, columnName: Plan, columnDataType: nvarchar(64) }

        - dropNotNullConstraint: {tableName: Membership, columnName: Type, columnDataType: nvarchar(64) }

        - dropNotNullConstraint: {tableName: Page, columnName: SourceType, columnDataType: nvarchar(64) }
        - dropNotNullConstraint: {tableName: Page, columnName: SourceConfiguration, columnDataType: nvarchar(64) }
        - dropNotNullConstraint: {tableName: Page, columnName: ConfigurationTryItURL, columnDataType: nvarchar(64) }

        - dropNotNullConstraint: {tableName: Plan, columnName: Type, columnDataType: nvarchar(64) }
        - dropNotNullConstraint: {tableName: Plan, columnName: Definition, columnDataType: nclob }
        - dropNotNullConstraint: {tableName: Plan, columnName: Status, columnDataType: nvarchar(64) }
        - dropNotNullConstraint: {tableName: Plan, columnName: Security, columnDataType: nvarchar(64) }

        - dropNotNullConstraint: {tableName: Subscription, columnName: SubscribedBy, columnDataType: nvarchar(64) }
        - dropNotNullConstraint: {tableName: Subscription, columnName: Reason, columnDataType: nvarchar(64) }
